#!/usr/bin/env python

import wx, guif

frame = guif.dispguif("Enter some text: %(edit)250t \n %(button)b", 
                      "", "Press me!",
                      ExitOn = ("button", wx.EVT_BUTTON))

guif.dispguif("You typed: %l", frame.edit.GetValue())

